POST http://localhost:8080/jwt/requestToken
accessToken: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0MyIsIm1lbWJlck51bWJlciI6IjQzIiwiZXhwIjoxNjM5NzE4ODE4fQ.ePrzONUtx7MUh8xVhULRUyZCUy_MQKkpbELvVoupcEDGMfHE_SwOeAJc_TqZmonnSUSNHcRNOO3OQfVNVbSZYA
refreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDAzMjE4MTh9.rgHiGgu5tQi_SNSnk4Ny8uZYAGRZK62Z7KSvJQFD6JM

